// <auto-generated />
namespace Kimserey.Rating.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class AddCountProfileView : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCountProfileView));
        
        string IMigrationMetadata.Id
        {
            get { return "201501211756230_AddCountProfileView"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
