// <auto-generated />
namespace Kimserey.Rating.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class addshowWelcometouser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addshowWelcometouser));
        
        string IMigrationMetadata.Id
        {
            get { return "201501201552333_add showWelcome to user"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
