// <auto-generated />
namespace Kimserey.Rating.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class IsDeactivated_In_UserEntity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IsDeactivated_In_UserEntity));
        
        string IMigrationMetadata.Id
        {
            get { return "201502260054504_IsDeactivated_In_UserEntity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
